name: Deploy Blue Version

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/week3-repo/blue:latest .

    - name: Push Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/week3-repo/blue:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
        --region ${{ secrets.GKE_REGION }} \
        --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Blue
      run: |
        kubectl apply -f k8s/blue-deployment.yaml
        kubectl apply -f k8s/service.yaml
